// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import FrameScrollOnLoadController from "./frame_scroll_on_load_controller"
application.register("frame-scroll-on-load", FrameScrollOnLoadController)
